"""数学パックの recipe 群（構成的生成・answer-first。実装設計 §6.1）。

サブモジュールを import することで `@register_recipe` の副作用を発火させ、
registry に登録する。
"""
from __future__ import annotations

from engine.packs.math.recipes import arithmetic  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import equation  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import linear  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import polynomial  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import letter_expr  # noqa: F401,E402  (polynomial のヘルパに依存＝後に import)
from engine.packs.math.recipes import radical  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import quadratic  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import rational_form  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import motion  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import quadratic_function  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import probability  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import proportion  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import proportion_graph  # noqa: F401,E402  (polynomial の _domain_candidates に依存＝後に import)
from engine.packs.math.recipes import statistics_distribution  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import distribution_chart  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import quartile  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import box_plot  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import sample_survey  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import exam_fusion  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import plane_geometry  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import plane_transform  # noqa: F401,E402  (letter_expr の _draw_distinct_points に依存＝後に import)
from engine.packs.math.recipes import angle_tracking  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import triangle_properties  # noqa: F401,E402  (letter_expr の _draw_distinct_points に依存＝後に import)
from engine.packs.math.recipes import congruence_correspondence  # noqa: F401,E402  (letter_expr の _draw_distinct_points に依存＝後に import)
from engine.packs.math.recipes import quadrilateral_properties  # noqa: F401,E402  (letter_expr の _draw_distinct_points に依存＝後に import)
from engine.packs.math.recipes import pythagorean  # noqa: F401,E402  (letter_expr の _draw_distinct_points に依存＝後に import)
from engine.packs.math.recipes import similarity  # noqa: F401,E402  (letter_expr の _draw_distinct_points に依存＝後に import)
from engine.packs.math.recipes import similarity_conditions  # noqa: F401,E402  (letter_expr の _draw_distinct_points に依存＝後に import)
from engine.packs.math.recipes import parallel_line_ratio  # noqa: F401,E402  (letter_expr の _draw_distinct_points に依存＝後に import)
from engine.packs.math.recipes import similarity_scale_ratio  # noqa: F401,E402  (letter_expr の draw に依存＝後に import)
from engine.packs.math.recipes import inscribed_angle  # noqa: F401,E402  (letter_expr の _draw_distinct_points に依存＝後に import)
from engine.packs.math.recipes import pythagorean_find_value  # noqa: F401,E402  (登録の副作用のため import)
from engine.packs.math.recipes import word_problem  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import word_problem_linear  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import word_problem_system  # noqa: F401  (word_problem_linear の _split_pair に依存＝後に import)
from engine.packs.math.recipes import word_problem_proportion  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import word_problem_quadratic  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import word_problem_sampling  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import word_problem_relation  # noqa: F401,E402  (word_problem_linear の _draw_pair_token に依存＝後に import)
from engine.packs.math.recipes import word_problem_expression  # noqa: F401,E402  (letter_expr/word_problem_linear の draw ヘルパに依存＝後に import)
from engine.packs.math.recipes import word_problem_linear_function  # noqa: F401,E402  (word_problem_linear の _split_pair に依存＝後に import)
from engine.packs.math.recipes import word_problem_probability  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import word_problem_proportion_frequency  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import word_problem_sqrt_misc  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import word_problem_quadratic_function  # noqa: F401,E402  (letter_expr の _draw_distinct_points に依存＝後に import)
from engine.packs.math.recipes import word_problem_pythagorean  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import solid_figure  # noqa: F401  (登録の副作用のため import)
from engine.packs.math.recipes import quadratic_function_graph  # noqa: F401,E402  (letter_expr/polynomial のヘルパに依存＝後に import)
from engine.packs.math.recipes import g1_space  # noqa: F401,E402  (letter_expr の _draw_distinct_points に依存＝後に import)

__all__: list[str] = []
